"""M1: input -> regions. Uses the synthetic samples in testbench/inputs/
(generated by testbench/generate_samples.py, run as a fixture below)."""
import os

import pytest

from src.regions.model import DigitizeScopeError
from src.regions.pipeline import load_and_extract_regions
from testbench.generate_samples import main as generate_samples

INPUTS = os.path.join(os.path.dirname(__file__), "..", "testbench", "inputs")


@pytest.fixture(scope="module", autouse=True)
def ensure_samples():
    if not os.path.exists(os.path.join(INPUTS, "circle_2color.png")):
        generate_samples()


def test_circle_raster_single_region():
    rs = load_and_extract_regions(os.path.join(INPUTS, "circle_2color.png"))
    assert len(rs.regions) == 1
    assert len(rs.colors) == 1
    assert not rs.warnings


def test_star_raster_two_colors_two_regions():
    rs = load_and_extract_regions(os.path.join(INPUTS, "star_3color.png"))
    assert len(rs.regions) == 2
    assert len(rs.colors) == 2


def test_text_sample_produces_letter_regions():
    rs = load_and_extract_regions(os.path.join(INPUTS, "text_sample.png"))
    assert len(rs.regions) >= 2  # "H" and "I" as separate components
    for r in rs.regions:
        height_mm = r.polygon.bounds[3] - r.polygon.bounds[1]
        assert height_mm >= 6.0  # in-scope cap height


def test_svg_two_shapes_two_colors():
    rs = load_and_extract_regions(os.path.join(INPUTS, "logo.svg"))
    assert len(rs.regions) == 2
    assert len(rs.colors) == 2
    assert rs.width_mm == pytest.approx(70.0, abs=0.5)
    assert rs.height_mm == pytest.approx(40.0, abs=0.5)


def test_small_text_rejected():
    with pytest.raises(DigitizeScopeError):
        load_and_extract_regions(
            os.path.join(INPUTS, "out_of_scope_smalltext.png"))
